import { Tree, logger } from '@nx/devkit';

export function createGitHubWorkflows(
  tree: Tree,
  workflowType: 'single' | 'two-step' | 'batch',
  projectNames: string[]
): void {
  if (workflowType === 'batch') {
    createBatchWorkflows(tree, projectNames);
  } else if (workflowType === 'two-step') {
    createTwoStepWorkflows(tree, projectNames);
  } else {
    createSingleWorkflow(tree, projectNames);
  }
}

function createBatchWorkflows(tree: Tree, projectNames: string[]): void {
  // Batch Release PR Workflow
  const batchReleasePRWorkflow = `name: Create Batch Release PR

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease
      baseBranch:
        description: 'Base branch to detect changes from'
        required: false
        type: string
        default: 'main'

jobs:
  create-batch-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: \${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create release branch
        id: branch
        run: |
          BRANCH_NAME="release/batch-\$(date +%Y-%m-%d-%H%M%S)"
          echo "branch=\$BRANCH_NAME" >> \$GITHUB_OUTPUT
          git checkout -b \$BRANCH_NAME

      - name: Version all affected projects
        run: |
          # Use nx affected to version all changed projects in one command
          npx nx affected --target=version \\
            --base=\${{ inputs.baseBranch }} \\
            --releaseAs=\${{ inputs.releaseType }} \\
            --gitCommit \\
            --ciOnly=false

      - name: Push release branch
        run: |
          git push origin \${{ steps.branch.outputs.branch }}

      - name: Create Pull Request
        run: |
          gh pr create \\
            --title "chore(release): batch release \$(date +%Y-%m-%d)" \\
            --body "## 📦 Batch Release\\n\\nThis PR includes version bumps for all affected projects.\\n\\n### Changes\\nSee individual commits for details.\\n\\n---\\n*Generated by nx-project-release*" \\
            --base \${{ inputs.baseBranch }} \\
            --head \${{ steps.branch.outputs.branch }} \\
            --label "release,automated"
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
`;

  tree.write('.github/workflows/batch-release-pr.yml', batchReleasePRWorkflow);
  logger.info('✅ Created .github/workflows/batch-release-pr.yml');

  // Batch Publish Workflow (triggered after PR merge)
  const batchPublishWorkflow = `name: Publish Batch Release

on:
  push:
    branches:
      - main
    paths:
      - '**/package.json'
      - '**/project.json'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: \${{ steps.check.outputs.has_changes }}
      base_commit: \${{ steps.base.outputs.commit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get merge base commit
        id: base
        run: |
          # Get the commit before the merge
          BASE=\$(git rev-parse HEAD^)
          echo "commit=\$BASE" >> \$GITHUB_OUTPUT

      - name: Check for version changes
        id: check
        run: |
          # Check if last commit is a merge commit
          if git log -1 --pretty=%B | grep -qE "^Merge pull request.*release"; then
            echo "has_changes=true" >> \$GITHUB_OUTPUT
          else
            echo "has_changes=false" >> \$GITHUB_OUTPUT
          fi

  publish:
    needs: detect-changes
    if: needs.detect-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build affected projects
        run: |
          npx nx affected --target=build \\
            --base=\${{ needs.detect-changes.outputs.base_commit }} \\
            --skip-nx-cache

      - name: Create tags and GitHub releases
        run: |
          npx nx affected --target=version \\
            --base=\${{ needs.detect-changes.outputs.base_commit }} \\
            --gitTag \\
            --githubRelease \\
            --ciOnly=false
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}

      - name: Publish affected projects
        run: |
          npx nx affected --target=publish \\
            --base=\${{ needs.detect-changes.outputs.base_commit }}
        env:
          # NPM Registry
          NODE_AUTH_TOKEN: \${{ secrets.NPM_TOKEN }}

          # Nexus Registry
          NEXUS_URL: \${{ secrets.NEXUS_URL }}
          NEXUS_REPOSITORY: \${{ secrets.NEXUS_REPOSITORY }}
          NEXUS_USERNAME: \${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: \${{ secrets.NEXUS_PASSWORD }}

          # S3 (OIDC recommended - configure AWS OIDC provider in repo settings)
          AWS_REGION: \${{ vars.AWS_REGION }}
          S3_BUCKET: \${{ vars.S3_BUCKET }}
          S3_PREFIX: \${{ vars.S3_PREFIX }}
          # Fallback: explicit credentials (not recommended)
          AWS_ACCESS_KEY_ID: \${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
`;

  tree.write('.github/workflows/batch-publish.yml', batchPublishWorkflow);
  logger.info('✅ Created .github/workflows/batch-publish.yml');

  // PR Validation with dry-run preview
  const prValidationWorkflow = `name: Validate Release PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  validate-and-preview:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run dry-run preview
        id: dryrun
        run: |
          # Skip if last commit is a release commit
          LAST_COMMIT_MSG=\$(git log -1 --pretty=%B)
          if echo "\$LAST_COMMIT_MSG" | grep -qE "^chore\\\\(release\\\\):"; then
            echo "Skipping: Last commit is a release commit"
            echo "output=Skipped (release commit)" >> \$GITHUB_OUTPUT
            echo "skip=true" >> \$GITHUB_OUTPUT
            exit 0
          fi

          # Run dry-run with --show
          OUTPUT=\$(npx nx affected --target=version \\
            --base=origin/main \\
            --dryRun --show 2>&1 || echo "Failed to run version preview")

          # Save output
          echo "\$OUTPUT" > /tmp/dryrun-output.txt
          echo "output_file=/tmp/dryrun-output.txt" >> \$GITHUB_OUTPUT

      - name: Comment PR with preview
        if: steps.dryrun.outputs.skip != 'true'
        uses: actions/github-script@v7
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const outputFile = '\${{ steps.dryrun.outputs.output_file }}';

            let body = '# 🎯 Batch Release Preview\\n\\n';
            body += 'This PR will make the following changes:\\n\\n';

            if (fs.existsSync(outputFile)) {
              const output = fs.readFileSync(outputFile, 'utf8');
              body += '\\`\\`\\`\\n' + output + '\\n\\`\\`\\`';
            } else {
              body += 'No version changes detected.';
            }

            body += '\\n\\n---\\n*This comment was automatically generated by nx-project-release*';

            // Find and update existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('Batch Release Preview')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }
`;

  tree.write('.github/workflows/pr-validation.yml', prValidationWorkflow);
  logger.info('✅ Created .github/workflows/pr-validation.yml');
}

function createTwoStepWorkflows(tree: Tree, projectNames: string[]): void {
  // Create PR validation workflow with dry-run comment
  const prValidationWorkflow = `name: Validate Release PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  validate-and-preview:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run version dry-run and capture output
        id: dryrun
        run: |
          # Skip if last commit is a release commit
          LAST_COMMIT_MSG=\$(git log -1 --pretty=%B)
          if echo "\$LAST_COMMIT_MSG" | grep -qE "^chore\\(release\\):"; then
            echo "Skipping: Last commit is a release commit"
            echo "output=Skipped (release commit)" >> \$GITHUB_OUTPUT
            echo "skip=true" >> \$GITHUB_OUTPUT
            exit 0
          fi

          # Detect changed projects
          CHANGED_FILES=\$(git diff --name-only origin/main...HEAD)
          PROJECTS=\$(echo "\$CHANGED_FILES" | grep -E '(package|project).json' | sed 's|/[^/]*$||' | sort -u)

          if [ -z "\$PROJECTS" ]; then
            echo "No projects detected"
            echo "output=No version changes detected" >> \$GITHUB_OUTPUT
            exit 0
          fi

          # Run dry-run with --show for each changed project
          OUTPUT=""
          for PROJECT in \$PROJECTS; do
            PROJECT_NAME=\$(basename \$PROJECT)
            echo "Running dry-run for: \$PROJECT_NAME"

            RESULT=\$(npx nx run \$PROJECT_NAME:version --dryRun --show 2>&1 || echo "Failed to run version for \$PROJECT_NAME")

            OUTPUT+="\n\n## 📦 \$PROJECT_NAME\n\n\`\`\`\n\$RESULT\n\`\`\`"
          done

          # Save output to file
          echo -e "\$OUTPUT" > /tmp/dryrun-output.txt
          echo "output_file=/tmp/dryrun-output.txt" >> \$GITHUB_OUTPUT

      - name: Comment PR with dry-run results
        uses: actions/github-script@v7
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const outputFile = '\${{ steps.dryrun.outputs.output_file }}';

            let body = '# 🎯 Release Preview\n\n';
            body += 'This PR will make the following changes:\n\n';

            if (fs.existsSync(outputFile)) {
              const output = fs.readFileSync(outputFile, 'utf8');
              body += output;
            } else {
              body += 'No version changes detected.';
            }

            body += '\n\n---\n*This comment was automatically generated by nx-project-release*';

            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('Release Preview')
            );

            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }
`;

  tree.write('.github/workflows/pr-validation.yml', prValidationWorkflow);
  logger.info('✅ Created .github/workflows/pr-validation.yml');

  // Create release PR workflow
  const releasePRWorkflow = `name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease
      project:
        description: 'Project to release (or "all" for workspace release)'
        required: true
        type: string
        default: 'all'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: \${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create release branch and version bump
        run: |
          if [ "\${{ github.event.inputs.project }}" = "all" ]; then
            npx nx run-many --target=version \\
              --all \\
              --releaseAs=\${{ github.event.inputs.releaseType }} \\
              --gitCommit \\
              --createReleaseBranch \\
              --gitPush \\
              --createPR \\
              --prLabels="release,automated" \\
              --ciOnly=false
          else
            npx nx run \${{ github.event.inputs.project }}:version \\
              --releaseAs=\${{ github.event.inputs.releaseType }} \\
              --gitCommit \\
              --createReleaseBranch \\
              --gitPush \\
              --createPR \\
              --prLabels="release,automated" \\
              --ciOnly=false
          fi
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
`;

  tree.write('.github/workflows/release-pr.yml', releasePRWorkflow);
  logger.info('✅ Created .github/workflows/release-pr.yml');

  // Create publish workflow (triggered on PR merge)
  const publishWorkflow = `name: Publish Release

on:
  push:
    branches:
      - main
    paths:
      - '**/package.json'
      - '**/project.json'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      projects: \${{ steps.detect.outputs.projects }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect changed projects
        id: detect
        run: |
          # Get changed files
          CHANGED_FILES=\$(git diff --name-only HEAD^ HEAD)

          # Extract project names from changed package.json/project.json
          PROJECTS=\$(echo "\$CHANGED_FILES" | grep -E '(package|project).json' | sed 's|/[^/]*$||' | sort -u | jq -R -s -c 'split("\\n")[:-1]')

          echo "projects=\$PROJECTS" >> \$GITHUB_OUTPUT
          echo "Changed projects: \$PROJECTS"

  publish:
    needs: detect-changes
    if: needs.detect-changes.outputs.projects != '[]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        project: \${{ fromJson(needs.detect-changes.outputs.projects) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npx nx run \${{ matrix.project }}:build --skip-nx-cache

      - name: Create GitHub Release
        run: |
          npx nx run \${{ matrix.project }}:version \\
            --gitTag \\
            --githubRelease \\
            --ciOnly=false
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: npx nx run \${{ matrix.project }}:publish
        env:
          NODE_AUTH_TOKEN: \${{ secrets.NPM_TOKEN }}
`;

  tree.write('.github/workflows/publish-release.yml', publishWorkflow);
  logger.info('✅ Created .github/workflows/publish-release.yml');
}

function createSingleWorkflow(tree: Tree, projectNames: string[]): void {
  const singleWorkflow = `name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease
      project:
        description: 'Project to release (or "all" for workspace release)'
        required: true
        type: string
        default: 'all'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: \${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Version and Build
        run: |
          if [ "\${{ github.event.inputs.project }}" = "all" ]; then
            npx nx run-many --target=version \\
              --all \\
              --releaseAs=\${{ github.event.inputs.releaseType }} \\
              --gitCommit \\
              --gitTag \\
              --gitPush \\
              --githubRelease \\
              --ciOnly=false

            npx nx run-many --target=build --all --skip-nx-cache
          else
            npx nx run \${{ github.event.inputs.project }}:version \\
              --releaseAs=\${{ github.event.inputs.releaseType }} \\
              --gitCommit \\
              --gitTag \\
              --gitPush \\
              --githubRelease \\
              --ciOnly=false

            npx nx run \${{ github.event.inputs.project }}:build --skip-nx-cache
          fi
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: |
          if [ "\${{ github.event.inputs.project }}" = "all" ]; then
            npx nx run-many --target=publish --all
          else
            npx nx run \${{ github.event.inputs.project }}:publish
          fi
        env:
          NODE_AUTH_TOKEN: \${{ secrets.NPM_TOKEN }}
`;

  tree.write('.github/workflows/release.yml', singleWorkflow);
  logger.info('✅ Created .github/workflows/release.yml');
}